Controllers/CalendarController.cs
using System;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Data.Entities;
using Data.Interfaces;
using Data.Repositories;
using DayPilot.Web.Mvc.Json;
using KwasantWeb.Controllers.DayPilot;
using KwasantWeb.ViewModels;
using Microsoft.AspNet.Identity;
using StructureMap;

namespace KwasantWeb.Controllers
{
    [HandleError]
    public class CalendarController : Controller
    {
        #region "Action"

        public ActionResult Index(int id = 0)
        {
            if (id <= 0)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            using (var uow = ObjectFactory.GetInstance<IUnitOfWork>())
            {
                IBookingRequestRepository bookingRequestRepository = uow.BookingRequestRepository;
                var bookingRequestDO = bookingRequestRepository.GetByKey(id);
                if (bookingRequestDO == null)
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

                return View(bookingRequestDO);
            }
        }

        public ActionResult Day(int bookingRequestID)
        {
            return new DayPilotCalendarControl(bookingRequestID).CallBack(this);
        }

        public ActionResult Month(int bookingRequestID)
        {
            return new DayPilotMonthControl(bookingRequestID).CallBack(this);
        }  

        public ActionResult Rtl()
        {
            return View();
        }
        public ActionResult Columns50()
        {
            return View();
        }
        public ActionResult Height100Pct()
        {
            return View();
        }

        public ActionResult Notify()
        {
            return View();
        }

        public ActionResult Crosshair()
        {
            return View();
        }

        public ActionResult ThemeBlue()
        {
            return View();
        }

        public ActionResult ThemeGreen()
        {
            return View();
        }

        public ActionResult ThemeWhite()
        {
            return View();
        }

        public ActionResult ThemeTraditional()
        {
            return View();
        }

        public ActionResult ThemeTransparent()
        {
            return View();
        }

        public ActionResult TimeHeaderCellDuration()
        {
            return View();
        }

        public ActionResult ActiveAreas()
        {
            return View();
        }

        public ActionResult JQuery()
        {
            return View();
        }

        public ActionResult HeaderAutoFit()
        {
            return View();
        }

        public ActionResult ExternalDragDrop()
        {
            return View();
        }

        public ActionResult EventArrangement()
        {
            return View();
        }

        public ActionResult AutoRefresh()
        {
            return View();
        }

        public ActionResult Today()
        {
            return View();
        }

        public ActionResult DaysResources()
        {
            return View();
        }

        public ActionResult Resources()
        {
            return View();
        }

        public ActionResult ContextMenu()
        {
            return View();
        }

        public ActionResult Message()
        {
            return View();
        }

        public ActionResult DayRange()
        {
            return View();
        }

        public ActionResult EventSelecting()
        {
            return View();
        }

        public ActionResult AutoHide()
        {
            return View();
        }

        public ActionResult GoogleLike()
        {
            return View();
        }

        public ActionResult RecurringEvents()
        {
            return View();
        }

        public ActionResult ThemeSilver()
        {
            return RedirectToAction("ThemeTraditional");
        }

        public ActionResult ThemeGreenWithBar()
        {
            return RedirectToAction("ThemeGreen");
        }

        public ActionResult Outlook2000()
        {
            return RedirectToAction("ThemeTraditional");
        }

        public ActionResult Backend(int bookingRequestID)
        {
            return new DayPilotCalendarControl(bookingRequestID).CallBack(this);
        }

        public ActionResult NavigatorBackend()
        {
            return new DayPilotNavigatorControl().CallBack(this);
        }
        #endregion "DayPilot-Related Methods"
    }
}

Controllers/EmailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Web.Routing;
using Data.Entities;
using Data.Entities.Enumerations;
using Data.Infrastructure;
using Data.Interfaces;
using Data.Repositories;
using KwasantCore.Managers.APIManager.Packagers.Kwasant;
using Utilities;
using Utilities.Logging;

namespace KwasantWeb.Controllers
{
    public class EmailController : Controller
    {
        private IUnitOfWork _uow;
        private IBookingRequestRepository curBookingRequestRepository;
        private KwasantPackager API;

        KwasantDbContext db = new KwasantDbContext();

        public EmailController(IUnitOfWork uow)
        {
            _uow = uow;
            curBookingRequestRepository = _uow.BookingRequestRepository;
            API = new KwasantPackager();
        }

        // GET: /Email/
        public ActionResult Index()
        {
            return View(curBookingRequestRepository.GetAll().Where(e => e.Status == EmailStatus.UNPROCESSED).OrderByDescending(e => e.Id).ToList());                        
        }

        // GET: /Email/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookingRequestDO bookingRequestDO = curBookingRequestRepository.GetByKey(id);

            if (bookingRequestDO == null)
            {
                return HttpNotFound();
            }
            else
            {
                //Redirect to Calendar control to open Booking Agent UI. It takes email id as parameter to which email message will be dispalyed in the left column of Booking Agent UI
                return RedirectToAction("Index", new RouteValueDictionary(new { controller = "Calendar", action = "Index", id = id }));
            }
            //return View(email);
        }

        // GET: /Email/
        [HttpGet]
        public string ProcessGetEmail(string requestString)
        {
            Dictionary<string, string> param = new Dictionary<string, string>();
            API.UnpackGetEmail(requestString, out param);
            EmailDO thisEmailDO = curBookingRequestRepository.GetByKey(param["Id"].ToInt());
            return API.PackResponseGetEmail(thisEmailDO);
        }
    }
}

Views/Calendar/AutoHide.cshtml
@using DayPilot.Web.Mvc
@using DayPilot.Web.Mvc.Enums.Calendar
@using DayPilot.Web.Mvc.Enums.Navigator
@using DayPilot.Web.Mvc.Events.Calendar

@section TitleContent {	Auto-Hiding Non-Business Hours (Calendar) }

<div class="note"><b>Note:</b> Non-business hours are hidden if there are not events to be displayed using HideFreeCells=true</div>

<div class="left-column">
    @Html.DayPilotNavigator("dpn", new DayPilotNavigatorConfig { 
        ShowMonths = 3,
        SkipMonths = 3,
        ShowWeekNumbers = true,
        BoundDayPilot = "dpc",
        SelectMode = NavigatorSelectMode.Week
        })
</div>

<div class="right-column">
    @Html.DayPilotBubble("bubble")

    @Html.DayPilotCalendar("dpc", new DayPilotCalendarConfig
    {
        ViewType = DayPilot.Web.Mvc.Enums.Calendar.ViewType.Week,
        BackendUrl = Url.Content("~/Calendar/Backend"),
        TimeRangeSelectedHandling = TimeRangeSelectedHandlingType.CallBack,
        EventDeleteHandling = EventDeleteHandlingType.CallBack,
        EventMoveHandling = EventMoveHandlingType.CallBack,
        ShowAllDayEvents = true,
        Height = 400,
        EventBubble = "bubble",
               
        HideFreeCells = true,
        HeightSpec = HeightSpec.Full
                                                           
    })
</div>

Views/Calendar/ContextMenu.cshtml
@using DayPilot.Web.Mvc
@using DayPilot.Web.Mvc.Enums
@using DayPilot.Web.Mvc.Enums.Calendar
@using DayPilot.Web.Mvc.Enums.Navigator
@using DayPilot.Web.Mvc.Events.Calendar

@section TitleContent { Context Menu (Calendar) }

<div class="left-column">
    @Html.DayPilotNavigator("dpn", new DayPilotNavigatorConfig { 
        ShowMonths = 3,
        SkipMonths = 3,
        ShowWeekNumbers = true,
        BoundDayPilot = "dpc",
        SelectMode = NavigatorSelectMode.Week
    })
</div>

<div class="right-column">
    @Html.DayPilotBubble("bubble")

    @Html.DayPilotMenu("menu1", new DayPilotMenuConfig
    {
        Items = new DayPilot.Web.Mvc.MenuItemCollection()
        {
            new DayPilot.Web.Mvc.MenuItem { Text = "Open", Action = MenuItemAction.JavaScript, JavaScript = "alert(e.value());"},
            new DayPilot.Web.Mvc.MenuItem { Text = "Delete", Action = MenuItemAction.CallBack, Command = "Delete"}
        }
    })

    @Html.DayPilotMenu("menu2", new DayPilotMenuConfig
    {
        Items = new DayPilot.Web.Mvc.MenuItemCollection()
        {
            new DayPilot.Web.Mvc.MenuItem { Text = "Open", Action = MenuItemAction.JavaScript, JavaScript = "alert(e.value());"}
        }
    })
        

    @Html.DayPilotCalendar("dpc_menu", new DayPilotCalendarConfig
    {
        ViewType = DayPilot.Web.Mvc.Enums.Calendar.ViewType.Week,
        BackendUrl = Url.Content("~/Calendar/Backend"),
        EventDeleteHandling = EventDeleteHandlingType.CallBack,
        EventMoveHandling = EventMoveHandlingType.CallBack,
        EventResizeHandling = EventResizeHandlingType.CallBack,
        TimeRangeSelectedHandling = TimeRangeSelectedHandlingType.CallBack,
        ShowAllDayEvents = true,
        Height = 400,
        HeightSpec = HeightSpec.Parent100Pct,
        EventBubble = "bubble",
        ContextMenu = "menu1"
    })
</div>

Views/Calendar/DayRange.cshtml
@using DayPilot.Web.Mvc
@using DayPilot.Web.Mvc.Enums.Calendar
@using DayPilot.Web.Mvc.Enums.Navigator
@using DayPilot.Web.Mvc.Events.Calendar

@section TitleContent {	Visible Day Range (Calendar) }


<div class="note"><b>Note:</b> The visible day range is set to 7:00 - 20:00 using DayBeginsHour and DayEndsHour.</div>

<div class="left-column">
    @Html.DayPilotNavigator("dpn", new DayPilotNavigatorConfig { 
        ShowMonths = 3,
        SkipMonths = 3,
            
        ShowWeekNumbers = true,
        BoundDayPilot = "dpc",
        SelectMode = NavigatorSelectMode.Week
        })
</div>

<div class="right-column">
    
    @Html.DayPilotBubble("bubble")

    @Html.DayPilotCalendar("dpc", new DayPilotCalendarConfig
        {

            ViewType = DayPilot.Web.Mvc.Enums.Calendar.ViewType.Week,
            BackendUrl = Url.Content("~/Calendar/Backend"),
            TimeRangeSelectedHandling = TimeRangeSelectedHandlingType.CallBack,
            EventDeleteHandling = EventDeleteHandlingType.CallBack,
            EventMoveHandling = EventMoveHandlingType.CallBack,
            ShowAllDayEvents = true,
            Height = 400,
            EventBubble = "bubble",
               
            DayBeginsHour = 7,
            DayEndsHour = 20,
            HeightSpec = HeightSpec.Full
        })

</div>

Views/Calendar/DaysResources.cshtml
@using DayPilot.Web.Mvc
@using DayPilot.Web.Mvc.Enums.Navigator
@using DayPilot.Web.Mvc.Events.Calendar

@section TitleContent {	Days-Resources View (Calendar) }


<div class="left-column">
    @Html.DayPilotNavigator("dpn", new DayPilotNavigatorConfig { 
        ShowMonths = 3,
        SkipMonths = 3,
            
        ShowWeekNumbers = true,
        BoundDayPilot = "dpc",
        SelectMode = NavigatorSelectMode.Week
        })
</div>

<div class="right-column">
            
    @Html.DayPilotBubble("bubble")

    @Html.DayPilotCalendar("days_resources", new DayPilotCalendarConfig
        {
            ViewType = DayPilot.Web.Mvc.Enums.Calendar.ViewType.Resources,
            HeaderLevels = 2,
            BackendUrl = Url.Content("~/Calendar/Backend"),
            TimeRangeSelectedHandling = TimeRangeSelectedHandlingType.JavaScript,
            TimeRangeSelectedJavaScript = "alert(start + ' ' + end + ' ' + resource);",

            EventDeleteHandling = EventDeleteHandlingType.CallBack,
            EventMoveHandling = EventMoveHandlingType.CallBack,
            Height = 400,
            EventBubble = "bubble"
        })

</div>

Views/Calendar/EventArrangement.cshtml
@using DayPilot.Web.Mvc
@using DayPilot.Web.Mvc.Enums.Navigator
@using DayPilot.Web.Mvc.Events.Calendar

@section TitleContent {	Event Arrangement (Calendar) }

<script type="text/javascript">
function arrangement(type) {
    dpc.eventArrangement = type;
    dpc.commandCallBack("refresh");
}
</script>

<div class="tip">
    Event arrangement: 
    <a href="javascript:arrangement('Full');">Full</a>
    |
    <a href="javascript:arrangement('Cascade');">Cascade</a>
    |
    <a href="javascript:arrangement('SidyBySide');">Side by Side</a>
</div>

<div class="left-column">
    @Html.DayPilotNavigator("dpn", new DayPilotNavigatorConfig { 
        ShowMonths = 3,
        SkipMonths = 3,
            
        ShowWeekNumbers = true,
        BoundDayPilot = "dpc",
        SelectMode = NavigatorSelectMode.Week
    })
</div>

<div class="right-column">
    @Html.DayPilotBubble("bubble")
    @Html.DayPilotCalendar("dpc", new DayPilotCalendarConfig
    {
        ViewType = DayPilot.Web.Mvc.Enums.Calendar.ViewType.Week,
        BackendUrl = Url.Content("~/Calendar/Backend"),
        EventDeleteHandling = EventDeleteHandlingType.CallBack,
        EventMoveHandling = EventMoveHandlingType.CallBack,
        EventResizeHandling = EventResizeHandlingType.CallBack,
        TimeRangeSelectedHandling = TimeRangeSelectedHandlingType.CallBack,
        ShowAllDayEvents = true,
        Height = 400,
        EventBubble = "bubble"
    })
</div>

Views/Calendar/EventSelecting.cshtml
@using DayPilot.Web.Mvc
@using DayPilot.Web.Mvc.Enums.Navigator
@using DayPilot.Web.Mvc.Events.Calendar

@section TitleContent {	Event Selecting (Calendar) }



<div class="left-column">
    @Html.DayPilotNavigator("dpn", new DayPilotNavigatorConfig { 
        ShowMonths = 3,
        SkipMonths = 3,
        ShowWeekNumbers = true,
        BoundDayPilot = "dpc",
        SelectMode = NavigatorSelectMode.Week,
        })
</div>

<div class="right-column">
    @Html.DayPilotBubble("bubble")

    @Html.DayPilotCalendar("dpc", new DayPilotCalendarConfig
        {
            ViewType = DayPilot.Web.Mvc.Enums.Calendar.ViewType.Week,
            BackendUrl = Url.Content("~/Calendar/Backend"),
            EventClickHandling = EventClickHandlingType.Select,
            EventSelectHandling = EventSelectHandlingType.JavaScript,
            EventDeleteHandling = EventDeleteHandlingType.CallBack,
            EventMoveHandling = EventMoveHandlingType.CallBack,
            EventResizeHandling = EventResizeHandlingType.CallBack,
            TimeRangeSelectedHandling = TimeRangeSelectedHandlingType.CallBack,
            ShowAllDayEvents = true,
            Height = 400,
            EventBubble = "bubble"
        })
</div>

Views/Calendar/Index.cshtml
@model Data.Entities.EmailDO
@using DayPilot.Web.Mvc
@using DayPilot.Web.Mvc.Enums
@using DayPilot.Web.Mvc.Enums.Calendar
@using DayPilot.Web.Mvc.Events.Calendar
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }
@{
    ViewBag.Title = "Event ";
}
@section styles{
    <style type="text/css">
    body {
        padding-top: 50px;
        padding-bottom: 20px;
    }

    /* Set padding to keep content from hitting the edges */
    .body-content {
        padding-left: 15px;
        padding-right: 15px;
    }

    /* Set width on the form input elements since they're 100% wide by default */
    input,
    select,
    textarea {
        max-width: 280px;
    }

    /* styles for validation helpers */
    .field-validation-error {
        color: #b94a48;
    }

    .field-validation-valid {
        display: none;
    }

    input.input-validation-error {
        border: 1px solid #b94a48;
    }

    input[type="checkbox"].input-validation-error {
        border: 0 none;
    }

    .validation-summary-errors {
        color: #b94a48;
    }

    .validation-summary-valid {
        display: none;
                        }

    .bookingAgentFormControlBorder {
        border: 2px solid gray;
        text-align: left;
        padding-left: 2px;
        color: #000000;
        font-size: 0.85em;
        font-weight: normal;
        min-height: 35px;
    }

    .label_vertical_alignment {
        position: relative;
        top: 10px;
    }

    .container_box {
        border: 2px solid gray;
        padding-left: 20px;
        min-height: 800px;
    }

    .mid_container_text {
        font-size: 0.85em;
    }

    .divider_height {
        height: 20px;
    }


    .bookingAgentFormControlBorder {
        border: 2px solid gray;
        text-align: left;
        padding-left: 2px;
        color: #000000;
        font-size: 0.85em;
        font-weight: normal;
        min-height: 50px;
        overflow-x: auto;
                        }

    #toolbar {
        margin: 10px 0px 20px 0px;
        width: 174px;
        border: none;
        background: none;
        position: relative;
    }

        #toolbar a {
            display: inline-block;
            height: 35px;
            text-decoration: none;
            padding: 5px;
            color: #666;
            border: 1px solid #aaa;
            background: -webkit-gradient(linear, left top, left bottom, from(#fafafa), to(#e2e2e2));
            background: -webkit-linear-gradient(top, #fafafa 0%, #e2e2e2);
            background: -moz-linear-gradient(top, #fafafa 0%, #e2e2e2);
            background: -ms-linear-gradient(top, #fafafa 0%, #e2e2e2);
            background: -o-linear-gradient(top, #fafafa 0%, #e2e2e2);
            background: linear-gradient(top, #fafafa 0%, #e2e2e2);
            filter: progid:DXImageTransform.Microsoft.Gradient(startColorStr="#fafafa", endColorStr="#e2e2e2");
        }
</style>
@Styles.Render("~/bundles/css/daypilot")
@Styles.Render("~/bundles/css/default")
@Styles.Render("~/bundles/css/bootstrap3.0")
}
@section immediateScripts
{
    @Scripts.Render("~/bundles/js/jquery")
@Scripts.Render("~/bundles/js/daypilot")
}
@section scripts
{
    @Scripts.Render("~/bundles/js/modernizr")
@Scripts.Render("~/bundles/js/bootstrap")
@Scripts.Render("~/bundles/js/common")
}
<div class="jumbotron" style="padding-left:20px; padding-right:20px; width: 1270px;">
            <div class="row">
        <div id="emailInfoBox" class="col-md-4 container_box" style="height:100%; padding:0px;width:420px;border:none;">
            <iframe src="/Api/GetEmailHTML.aspx?emailID=@Model.Id" style="width:100%;height:100%;border:none;margin-top:-7px;"></iframe>
        </div>

        <div id="divCalender" class="col-md-6 container_box" style="padding-bottom: 79px;">
            <div class="row">
                <div id="toolbar" style="width:100%; font-size:12px;">
                    <a href="#" id="toolbar_day">Day</a>
                    <a href="#" id="toolbar_week">Week</a>
                    <a href="#" id="toolbar_month">Month</a>
                </div>
            </div>
            <div class="row">
                <div style="padding-right:5px">
                    @Html.DayPilotMenu("menu1", new DayPilotMenuConfig
                    {
                        Items = new MenuItemCollection()
                        {
                            new MenuItem { Text = "Delete", Action = MenuItemAction.JavaScript, JavaScript = "eventDelete(e)"}
                        }
                    })

                    @Html.DayPilotMenu("menu2", new DayPilotMenuConfig
                    {
                        Items = new MenuItemCollection()
                        {
                            new MenuItem { Text = "Open", Action = MenuItemAction.JavaScript, JavaScript = "alert(e.value());"}
                        }
                    })

                    @Html.DayPilotBubble("bubble")

                    @Html.DayPilotCalendar("dp_day", new DayPilotCalendarConfig
                    {
                        BackendUrl = Url.Content("~/Calendar/Day?bookingRequestID=" + Model.Id),
                        
                        EventMoveHandling = EventMoveHandlingType.JavaScript,
                        EventResizeHandling = EventResizeHandlingType.JavaScript,
                        TimeRangeSelectedHandling = TimeRangeSelectedHandlingType.JavaScript,
                        EventClickHandling = EventClickHandlingType.JavaScript,
                        HeaderClickHandling = HeaderClickHandlingType.JavaScript,
                        EventDeleteHandling = EventDeleteHandlingType.JavaScript,
                        
                        EventBackColor = "#638EDE",
                        DurationBarVisible = false,
                        EventHeaderVisible = false,
                        
                        Height = 550,
                        HeaderHeight = 50,
                        CellHeight = 25,
                        CssOnly = false,
                        ContextMenu = "menu1",
                        Theme = "calendar_white",
                        ViewType = DayPilot.Web.Mvc.Enums.Calendar.ViewType.Day,

                        EventClickJavaScript = "eventClick(e)",
                        EventMoveJavaScript = "eventMove(e, newStart, newEnd)",
                        EventResizeJavaScript = "eventMove(e, newStart, newEnd)",
                        TimeRangeSelectedJavaScript = "eventNew(start, end, resource)",
                        EventDeleteJavaScript = "eventDelete(e)",
                    })

                    @Html.DayPilotCalendar("dp_week", new DayPilotCalendarConfig
                    {
                        ViewType = DayPilot.Web.Mvc.Enums.Calendar.ViewType.Week,
                        BackendUrl = Url.Content("~/Calendar/Backend?bookingRequestID=" + Model.Id),
                        
                        EventMoveHandling = EventMoveHandlingType.JavaScript,
                        EventResizeHandling = EventResizeHandlingType.JavaScript,
                        TimeRangeSelectedHandling = TimeRangeSelectedHandlingType.JavaScript,
                        EventClickHandling = EventClickHandlingType.JavaScript,
                        HeaderClickHandling = HeaderClickHandlingType.JavaScript,
                        EventDeleteHandling = EventDeleteHandlingType.JavaScript,

                        EventBackColor = "#638EDE",
                        DurationBarVisible = false,
                        EventHeaderVisible = false,
                        
                        ShowAllDayEvents = true,
                        AllowMultiSelect = true,
                        Height = 550,
                        HeaderHeight = 30,
                        HeaderFontSize = "12px",
                        CssOnly = false,
                        Theme = "calendar_white",
                        HeightSpec = HeightSpec.BusinessHours,
                        EventBubble = "bubble",
                        EventClickJavaScript = "eventClick(e)",
                        EventMoveJavaScript = "eventMove(e, newStart, newEnd)",
                        EventResizeJavaScript = "eventMove(e, newStart, newEnd)",
                        TimeRangeSelectedJavaScript = "eventNew(start, end, resource)",
                        EventDeleteJavaScript = "eventDelete(e)",
                        ContextMenu = "menu1",
                        HeaderClickJavaScript = "alert('Day clicked: ' + c.date);"
                    })

                    @Html.DayPilotMonth("dp_month", new DayPilotMonthConfig
                    {
                        BackendUrl = Url.Content("~/Calendar/Month?bookingRequestID=" + Model.Id),

                        EventMoveHandling = DayPilot.Web.Mvc.Events.Month.EventMoveHandlingType.JavaScript,
                        EventResizeHandling = DayPilot.Web.Mvc.Events.Month.EventResizeHandlingType.JavaScript,
                        TimeRangeSelectedHandling = DayPilot.Web.Mvc.Events.Month.TimeRangeSelectedHandlingType.JavaScript,
                        EventClickHandling = DayPilot.Web.Mvc.Events.Month.EventClickHandlingType.JavaScript,
                        HeaderClickHandling = DayPilot.Web.Mvc.Events.Month.HeaderClickHandlingType.JavaScript,
                        
                        
                        EventFontSize = "10px",
                        
                        HeaderFontSize = "12px",
                        CellHeight = 90,
                        HeaderHeight = 50,
                        EventHeight = 50,
                        Height = "550",
                        CssOnly = false,
                        ContextMenu = "menu1",
                        Theme = "calendar_white",

                        EventClickJavaScript = "eventClick(e)",
                        EventMoveJavaScript = "eventMove(e, newStart, newEnd)",
                        EventResizeJavaScript = "eventMove(e, newStart, newEnd)",
                        TimeRangeSelectedJavaScript = "eventNew(start, end)",
                    })
                </div>
                
            </div>
        </div>
        
        <div class="col-lg-2 container_box" style="padding-top:53px; padding-bottom:101px; position:relative; float:left;">
            @Html.DayPilotNavigator("dp_navigator", new DayPilotNavigatorConfig
            {
                CssOnly = true,
                Theme = "navigator_white",
                ShowMonths = 1
            })
        </div>

    </div>
</div>
<div class="row">
    @Html.ActionLink("Back to booking requests", "Index", "Email")
</div>
<div class="row">
    @Html.ActionLink("Show Users", "Index", "User")
</div>


<script type="text/javascript">

    $("#toolbar_day").click(function () {
        $("#divCalender").css("padding-bottom", "79px");
    });

    $("#toolbar_week").click(function () {
        $("#divCalender").css("padding-bottom", "170px");
    });

    $("#toolbar_month").click(function () {
        $("#divCalender").css("padding-bottom", "79px");
    });

    var switcher = new DayPilot.Switcher();

    switcher.addView(dp_day);
    switcher.addView(dp_week);
    switcher.addView(dp_month);

    switcher.addButton("toolbar_day", dp_day);
    switcher.addButton("toolbar_week", dp_week);
    switcher.addButton("toolbar_month", dp_month);

    switcher.addNavigator(dp_navigator);

    switcher.show(dp_day);
    

    function displayForm(url) {
        var m = new DayPilot.Modal();
        m.top = 130;
        m.width = 580;
        m.closed = function () {
            var daypilotControls = [
                dp_day,
                dp_week,
                dp_month
            ];

            if (this.result == "OK") {
                $.each(daypilotControls, function (i, ele) {
                    ele.commandCallBack('refresh');
                });
            }
            $.each(daypilotControls, function (i, ele) {
                ele.clearSelection('refresh');
            });
        };

        m.showUrl(url);
    }

    function eventClick(e) {
        displayForm(getBaseURL() + '/Event/Edit/?eventID=' + e.id());
    }

    function eventNew(start, end) {
        displayForm(getBaseURL() + '/Event/New/?bookingRequestID=' + @Model.Id + '&start=' + start + '&end=' + end);
    }

    function eventMove(e, newStart, newEnd) {
        displayForm(getBaseURL() + '/Event/MoveEvent/?eventID=' + e.id() + '&newStart=' + newStart + '&newEnd=' + newEnd);
    }

    function eventDelete(e) {
        displayForm(getBaseURL() + '/Event/DeleteEvent/?eventID=' + e.id());
    }

</script>